Repository SSAFY-TOTT/Backend, pull requests merged in 2023-09, with the labels that each got.

#4 프로젝트의 도메인 계층을 구현
  build.gradle
  docs/Github.md
  src/main/java/com/ssafy/tott/TottApplication.java
  src/main/java/com/ssafy/tott/account/domain/Account.java
  src/main/java/com/ssafy/tott/account/domain/AccountRepository.java
  src/main/java/com/ssafy/tott/global/domain/BaseEntity.java
  src/main/java/com/ssafy/tott/housedetail/domain/HouseDetail.java
  src/main/java/com/ssafy/tott/housedetail/domain/HouseDetailRepository.java
  src/main/java/com/ssafy/tott/housegeo/domain/HouseGeo.java
  src/main/java/com/ssafy/tott/housegeo/domain/HouseGeoRepository.java
  src/main/java/com/ssafy/tott/member/domain/Member.java
  src/main/java/com/ssafy/tott/member/domain/MemberRepository.java
  src/main/java/com/ssafy/tott/member/domain/embbeded/Email.java
  src/main/java/com/ssafy/tott/member/domain/embbeded/Password.java
  src/main/java/com/ssafy/tott/member/domain/embbeded/PhoneNumber.java
  src/main/java/com/ssafy/tott/region/domain/Region.java
  src/main/java/com/ssafy/tott/region/domain/RegionRepository.java
  src/main/java/com/ssafy/tott/wishlist/domain/Wishlist.java
  src/main/java/com/ssafy/tott/wishlist/domain/WishlistRepository.java
  src/main/resources/application.yml
Labels: ✨ feature

#9 Custom Exception 생성
  src/main/java/com/ssafy/tott/global/exception/ControllerAdvice.java
  src/main/java/com/ssafy/tott/global/exception/ErrorCode.java
  src/main/java/com/ssafy/tott/global/exception/TOTTException.java
  src/main/java/com/ssafy/tott/global/exception/dto/response/ExceptionResponse.java
Labels: ✨ feature

#8 Kakao API 를 호출하여 주소를 좌표로 변환
  src/main/java/com/ssafy/tott/api/kakao/data/Documents.java
  src/main/java/com/ssafy/tott/api/kakao/data/KakaoAPIResponse.java
  src/main/java/com/ssafy/tott/api/kakao/module/KakaoMapAPI.java
  src/main/java/com/ssafy/tott/api/kakao/property/KakaoAddressProperties.java
  src/main/java/com/ssafy/tott/api/kakao/property/KakaoProperties.java
  src/main/java/com/ssafy/tott/api/kakao/util/KakaoApiConfiguration.java
  src/main/resources/application.yml
Labels: ✨ feature

#11 회원의 데이터를 검증하는 기능을 구현
  src/main/java/com/ssafy/tott/member/domain/embbeded/Email.java
  src/main/java/com/ssafy/tott/member/domain/embbeded/Password.java
  src/main/java/com/ssafy/tott/member/domain/embbeded/PhoneNumber.java
  src/test/java/com/ssafy/tott/TottApplicationTests.java
  src/test/java/com/ssafy/tott/member/domain/embbeded/EmailTest.java
  src/test/java/com/ssafy/tott/member/domain/embbeded/PasswordTest.java
  src/test/java/com/ssafy/tott/member/domain/embbeded/PhoneNumberTest.java
Labels: ✨ feature, ✅ test

#16 공공데이터 API 연동 및 파싱
  build.gradle
  src/main/java/com/ssafy/tott/api/seoul/data/RentApiModel.java
  src/main/java/com/ssafy/tott/api/seoul/data/RentData.java
  src/main/java/com/ssafy/tott/api/seoul/data/RentRow.java
  src/main/java/com/ssafy/tott/api/seoul/module/HouseAPI.java
  src/main/resources/application.yml
  src/test/java/com/ssafy/tott/api/seoul/HouseAPITest.java
Labels: ✨ feature

#18 회원가입 기능 구현
  build.gradle
  src/main/java/com/ssafy/tott/account/domain/Account.java
  src/main/java/com/ssafy/tott/account/domain/BankCode.java
  src/main/java/com/ssafy/tott/account/domain/embbeded/AccountNumber.java
  src/main/java/com/ssafy/tott/account/exception/AccountErrorCode.java
  src/main/java/com/ssafy/tott/account/exception/AccountException.java
  src/main/java/com/ssafy/tott/api/APICore.java
  src/main/java/com/ssafy/tott/api/shinhan/ShinhanBankAPI.java
  src/main/java/com/ssafy/tott/api/shinhan/dto/DataBody.java
  src/main/java/com/ssafy/tott/api/shinhan/dto/ShinhanBankDataBody.java
  src/main/java/com/ssafy/tott/api/shinhan/dto/request/ShinhanBankAPIRequest.java
  src/main/java/com/ssafy/tott/api/shinhan/dto/response/ShinhanBankAPIResponse.java
  src/main/java/com/ssafy/tott/api/shinhan/dto/response/header/ResponseDataHeader.java
  src/main/java/com/ssafy/tott/api/shinhan/factory/ShinhanBankWebClientFactory.java
  src/main/java/com/ssafy/tott/api/shinhan/service/searchname/ShinhanBankSearchNameAPI.java
  src/main/java/com/ssafy/tott/api/shinhan/service/searchname/dto/request/SearchNameRequestDataBody.java
  src/main/java/com/ssafy/tott/api/shinhan/service/searchname/dto/request/SearchNameRequestShinhanBankDataBody.java
  src/main/java/com/ssafy/tott/api/shinhan/service/searchname/dto/response/ShinhanBankSearchNameResponse.java
  src/main/java/com/ssafy/tott/api/shinhan/service/searchname/dto/response/body/SearchNameResponseShinhanBankDataBody.java
  src/main/java/com/ssafy/tott/api/shinhan/service/transfer1/ShinhanBankTransfer1API.java
  src/main/java/com/ssafy/tott/api/shinhan/service/transfer1/dto/request/Transfer1RequestDataBody.java
  src/main/java/com/ssafy/tott/api/shinhan/service/transfer1/dto/request/Transfer1RequestShinhanBankDataBody.java
  src/main/java/com/ssafy/tott/api/shinhan/service/transfer1/dto/response/ShinhanBankTransfer1Response.java
  src/main/java/com/ssafy/tott/api/shinhan/service/transfer1/dto/response/body/Transfer1ResponseDataBody.java
  src/main/java/com/ssafy/tott/api/shinhan/service/transfer1/dto/response/body/Transfer1ResponseShinhanBankDataBody.java
  src/main/java/com/ssafy/tott/global/domain/BaseEntity.java
  src/main/java/com/ssafy/tott/global/redis/RedisConfig.java
  src/main/java/com/ssafy/tott/member/controller/MemberController.java
  src/main/java/com/ssafy/tott/member/domain/MemberVerificationCache.java
  src/main/java/com/ssafy/tott/member/domain/MemberVerificationCacheRepository.java
  src/main/java/com/ssafy/tott/member/dto/request/MemberSignupRequest.java
  src/main/java/com/ssafy/tott/member/dto/request/MemberVerificationRequest.java
  src/main/java/com/ssafy/tott/member/dto/responsse/MemberSignupResponse.java
  src/main/java/com/ssafy/tott/member/dto/responsse/MemberVerificationResponse.java
  src/main/java/com/ssafy/tott/member/exception/MemberErrorCode.java
  src/main/java/com/ssafy/tott/member/exception/MemberException.java
  src/main/java/com/ssafy/tott/member/mapper/MemberMapper.java
  src/main/java/com/ssafy/tott/member/service/MemberService.java
  src/main/java/com/ssafy/tott/member/service/MemberVerificationService.java
  src/test/java/com/ssafy/tott/api/shinhan/ShinhanBankAPITest.java
  src/test/java/com/ssafy/tott/global/fixture/MemberFixture.java
  src/test/java/com/ssafy/tott/member/domain/MemberRepositoryTest.java
  src/test/java/com/ssafy/tott/member/service/MemberServiceTest.java
  src/test/java/com/ssafy/tott/member/service/MemberVerificationServiceTest.java
Labels: ✨ feature

#25 Kakao API 의존성 주입 문제 해결
  src/main/java/com/ssafy/tott/api/kakao/data/Documents.java
  src/main/java/com/ssafy/tott/api/kakao/module/KakaoMapAPI.java
  src/main/java/com/ssafy/tott/api/kakao/property/KakaoAddressProperties.java
  src/main/java/com/ssafy/tott/api/kakao/property/KakaoProperties.java
  src/main/java/com/ssafy/tott/api/kakao/util/KakaoApiConfiguration.java
Labels: 🐛 bug

#23 로그인 기능 구현
  build.gradle
  src/main/java/com/ssafy/tott/api/seoul/module/HouseAPI.java
  src/main/java/com/ssafy/tott/auth/annotation/Authenticated.java
  src/main/java/com/ssafy/tott/auth/annotation/AuthenticatedArgumentResolver.java
  src/main/java/com/ssafy/tott/auth/controller/AuthController.java
  src/main/java/com/ssafy/tott/auth/domain/AuthToken.java
  src/main/java/com/ssafy/tott/auth/domain/AuthTokenRepository.java
  src/main/java/com/ssafy/tott/auth/dto/request/LoginRequest.java
  src/main/java/com/ssafy/tott/auth/dto/response/TokenResponse.java
  src/main/java/com/ssafy/tott/auth/exception/AuthErrorCode.java
  src/main/java/com/ssafy/tott/auth/exception/AuthException.java
  src/main/java/com/ssafy/tott/auth/service/AuthService.java
  src/main/java/com/ssafy/tott/auth/service/CustomUserDetailService.java
  src/main/java/com/ssafy/tott/auth/support/JwtAccessDeniedHandler.java
  src/main/java/com/ssafy/tott/auth/support/JwtAuthenticationEntryPoint.java
  src/main/java/com/ssafy/tott/auth/support/JwtFilter.java
  src/main/java/com/ssafy/tott/auth/support/JwtSecurityConfig.java
  src/main/java/com/ssafy/tott/auth/support/TokenProvider.java
  src/main/java/com/ssafy/tott/auth/vo/AuthMember.java
  src/main/java/com/ssafy/tott/global/security/SecurityConfig.java
  src/main/java/com/ssafy/tott/member/domain/Member.java
  src/main/java/com/ssafy/tott/member/domain/MemberRepository.java
  src/main/java/com/ssafy/tott/member/domain/Role.java
  src/main/java/com/ssafy/tott/member/domain/embbeded/Password.java
  src/main/java/com/ssafy/tott/member/exception/MemberErrorCode.java
  src/main/java/com/ssafy/tott/member/mapper/MemberMapper.java
  src/main/java/com/ssafy/tott/member/service/MemberVerificationService.java
  src/main/resources/application.yml
  src/test/java/com/ssafy/tott/api/seoul/HouseAPITest.java
  src/test/java/com/ssafy/tott/auth/service/AuthServiceTest.java
  src/test/java/com/ssafy/tott/global/fixture/MemberFixture.java
  src/test/java/com/ssafy/tott/member/domain/embbeded/PasswordTest.java
Labels: ✨ feature, ✅ test, 🔧 config

#26 전세집 데이터 DB저장
  build.gradle
  src/main/java/com/ssafy/tott/api/kakao/module/KakaoMapAPI.java
  src/main/java/com/ssafy/tott/api/seoul/batch/service/SchedulerConfig.java
  src/main/java/com/ssafy/tott/api/seoul/module/HouseAPI.java
  src/main/java/com/ssafy/tott/api/seoul/service/SchedulerService.java
  src/main/java/com/ssafy/tott/housedetail/domain/HouseDetail.java
  src/main/java/com/ssafy/tott/housedetail/service/HouseDetailService.java
  src/main/java/com/ssafy/tott/housegeo/domain/HouseGeo.java
  src/main/java/com/ssafy/tott/housegeo/domain/HouseGeoRepository.java
  src/main/java/com/ssafy/tott/housegeo/service/HouseGeoService.java
  src/main/java/com/ssafy/tott/region/domain/Region.java
  src/main/java/com/ssafy/tott/region/domain/RegionRepository.java
  src/main/java/com/ssafy/tott/region/service/RegionService.java
  src/test/java/com/ssafy/tott/api/kakao/module/KakaoAPITest.java
  src/test/java/com/ssafy/tott/api/seoul/HouseAPITest.java
  src/test/java/com/ssafy/tott/api/seoul/batch/service/SchedulerServiceTest.java
  src/test/java/com/ssafy/tott/housedetail/repository/HouseDetailRepositoryTest.java
  src/test/java/com/ssafy/tott/housedetail/service/HouseDetailServiceTest.java
  src/test/java/com/ssafy/tott/housegeo/repository/HouseGeoRepositoryTest.java
  src/test/java/com/ssafy/tott/housegeo/service/HouseGeoServiceTest.java
  src/test/java/com/ssafy/tott/region/repository/RegionRepositoryTest.java
  src/test/java/com/ssafy/tott/region/service/RegionServiceTest.java
Labels: ✨ feature, ✅ test, 🔧 config

#30 계좌 조회 기능을 구현한다
  src/main/java/com/ssafy/tott/account/service/AccountService.java
  src/main/java/com/ssafy/tott/api/shinhan/ShinhanBankAPI.java
  src/main/java/com/ssafy/tott/api/shinhan/service/searchaccounts/dto/ShinhanBankSearchAccountsAPI.java
  src/main/java/com/ssafy/tott/api/shinhan/service/searchaccounts/dto/request/ShinhanBankSearchAccountsRequestBody.java
  src/main/java/com/ssafy/tott/api/shinhan/service/searchaccounts/dto/response/ShinhanBankSearchAccountsResponse.java
  src/main/java/com/ssafy/tott/api/shinhan/service/searchaccounts/dto/response/body/ShinhanBankSearchAccountsResponseAccount.java
  src/main/java/com/ssafy/tott/api/shinhan/service/searchaccounts/dto/response/body/ShinhanBankSearchAccountsResponseDataBody.java
  src/main/java/com/ssafy/tott/api/shinhan/service/searchamount/dto/request/SearchSavingAccountRequestShinhanBankDataBody.java
  src/main/java/com/ssafy/tott/api/shinhan/service/searchamount/dto/response/ShinhanBankSearchSavingAccountResponse.java
  src/main/java/com/ssafy/tott/api/shinhan/service/searchamount/dto/response/body/SearchSavingAccountResponseShinhanBankDataBody.java
Labels: ✨ feature

#32 테스트 코드 분리
  src/main/resources/application-test.yml
  src/test/java/com/ssafy/tott/api/kakao/module/KakaoAPITest.java
  src/test/java/com/ssafy/tott/api/seoul/HouseAPITest.java
  src/test/java/com/ssafy/tott/auth/service/AuthServiceTest.java
  src/test/java/com/ssafy/tott/housedetail/service/HouseDetailServiceTest.java
  src/test/java/com/ssafy/tott/housegeo/repository/HouseGeoRepositoryTest.java
  src/test/java/com/ssafy/tott/housegeo/service/HouseGeoServiceTest.java
  src/test/java/com/ssafy/tott/member/service/MemberServiceTest.java
  src/test/java/com/ssafy/tott/member/service/MemberVerificationServiceTest.java
  src/test/java/com/ssafy/tott/region/repository/RegionRepositoryTest.java
  src/test/java/com/ssafy/tott/region/service/RegionServiceTest.java
Labels: 📝 docs, ✅ test

#33 dockerizing
  Dockerfile
  build.gradle
  src/main/java/com/ssafy/tott/global/config/OpenApiConfig.java
Labels: ✨ feature

#36 예산 추가 기능 구현
  src/main/java/com/ssafy/tott/auth/service/AuthService.java
  src/main/java/com/ssafy/tott/auth/support/TokenProvider.java
  src/main/java/com/ssafy/tott/budget/controller/BudgetController.java
  src/main/java/com/ssafy/tott/budget/data/dto/requset/BudgetsUpdateRequest.java
  src/main/java/com/ssafy/tott/budget/data/dto/response/BudgetsResponse.java
  src/main/java/com/ssafy/tott/budget/data/vo/BudgetVO.java
  src/main/java/com/ssafy/tott/budget/domain/Budget.java
  src/main/java/com/ssafy/tott/budget/domain/BudgetRepository.java
  src/main/java/com/ssafy/tott/budget/service/BudgetService.java
  src/main/java/com/ssafy/tott/global/config/WebConfig.java
  src/main/java/com/ssafy/tott/member/domain/Member.java
  src/main/java/com/ssafy/tott/member/service/MemberService.java
  src/test/java/com/ssafy/tott/budget/domain/BudgetRepositoryTest.java
  src/test/java/com/ssafy/tott/budget/service/BudgetServiceTest.java
  src/test/java/com/ssafy/tott/global/config/ServiceTest.java
  src/test/java/com/ssafy/tott/global/fixture/BudgetFixture.java
  src/test/java/com/ssafy/tott/global/fixture/MemberFixture.java
  src/test/java/com/ssafy/tott/member/domain/MemberRepositoryTest.java
Labels: ✨ feature

#37 getGeoServiceTest 수정
  src/main/java/com/ssafy/tott/api/kakao/data/Documents.java
  src/main/java/com/ssafy/tott/api/seoul/batch/SchedulerConfig.java
  src/main/java/com/ssafy/tott/api/seoul/service/SchedulerService.java
  src/main/java/com/ssafy/tott/housedetail/mapper/HouseDetailMapper.java
  src/main/java/com/ssafy/tott/housedetail/service/HouseDetailService.java
  src/main/java/com/ssafy/tott/housegeo/domain/BuildingType.java
  src/main/java/com/ssafy/tott/housegeo/domain/HouseGeo.java
  src/main/java/com/ssafy/tott/housegeo/mapper/HouseGeoMapper.java
  src/main/java/com/ssafy/tott/housegeo/service/HouseGeoService.java
  src/main/java/com/ssafy/tott/region/mapper/RegionMapper.java
  src/main/java/com/ssafy/tott/region/service/RegionService.java
  src/test/java/com/ssafy/tott/api/seoul/service/SchedulerServiceTest.java
  src/test/java/com/ssafy/tott/housedetail/repository/HouseDetailRepositoryTest.java
  src/test/java/com/ssafy/tott/housedetail/service/HouseDetailServiceTest.java
  src/test/java/com/ssafy/tott/housegeo/repository/HouseGeoRepositoryTest.java
  src/test/java/com/ssafy/tott/housegeo/service/HouseGeoServiceTest.java
  src/test/java/com/ssafy/tott/region/repository/RegionRepositoryTest.java
  src/test/java/com/ssafy/tott/region/service/RegionServiceTest.java
Labels: 🚑 fix

#42 예적금 계좌 구분 및 저장, 사용자 정보에 추가한다
  src/main/java/com/ssafy/tott/account/service/AccountService.java
  src/main/java/com/ssafy/tott/api/shinhan/ShinhanBankAPI.java
  src/main/java/com/ssafy/tott/member/service/MemberService.java
Labels: ✨ feature

#48 google format github action 삭제
  .github/workflows/google-java-format.yml
Labels: 🚑 fix

#52 지도에 제공할 데이터를 조회
  build.gradle
  src/main/java/com/ssafy/tott/api/infra/SchedulerConfig.java
  src/main/java/com/ssafy/tott/api/seoulopendata/data/vo/RentRow.java
  src/main/java/com/ssafy/tott/housedetail/controller/HouseDetailController.java
  src/main/java/com/ssafy/tott/housedetail/domain/HouseDetail.java
  src/main/java/com/ssafy/tott/housegeo/controller/HouseGeoController.java
  src/main/java/com/ssafy/tott/housegeo/data/cond/HouseGeoFilterCond.java
  src/main/java/com/ssafy/tott/housegeo/data/dto/request/GeoSearchRequest.java
  src/main/java/com/ssafy/tott/housegeo/data/dto/response/HouseGeoSearchResponse.java
  src/main/java/com/ssafy/tott/housegeo/data/vo/HouseSearchDetailVO.java
  src/main/java/com/ssafy/tott/housegeo/data/vo/HouseSearchGeoVO.java
  src/main/java/com/ssafy/tott/housegeo/domain/HouseGeoRepository.java
  src/main/java/com/ssafy/tott/housegeo/domain/query/HouseGeoRepositoryCustom.java
  src/main/java/com/ssafy/tott/housegeo/domain/query/HouseGeoRepositoryImpl.java
  src/main/java/com/ssafy/tott/housegeo/service/HouseGeoService.java
  src/main/java/com/ssafy/tott/member/domain/MemberVerificationCacheRepository.java
  src/main/java/com/ssafy/tott/region/controller/RegionController.java
  src/main/java/com/ssafy/tott/region/data/cond/RegionFilterCond.java
  src/main/java/com/ssafy/tott/region/domain/RegionRepository.java
  src/main/java/com/ssafy/tott/region/domain/query/RegionRepositoryCustom.java
  src/main/java/com/ssafy/tott/region/domain/query/RegionRepositoryImpl.java
  src/main/java/com/ssafy/tott/region/exception/RegionErrorCode.java
  src/main/java/com/ssafy/tott/region/exception/RegionException.java
  src/main/java/com/ssafy/tott/region/service/RegionService.java
Labels: ✨ feature

#54 회원 중복가입 방지
  src/main/java/com/ssafy/tott/member/controller/MemberController.java
  src/main/java/com/ssafy/tott/member/data/cond/MemberExistBySignupCond.java
  src/main/java/com/ssafy/tott/member/data/dto/request/MemberSignupRequest.java
  src/main/java/com/ssafy/tott/member/data/dto/request/MemberVerificationRequest.java
  src/main/java/com/ssafy/tott/member/data/dto/responsse/MemberSignupResponse.java
  src/main/java/com/ssafy/tott/member/data/dto/responsse/MemberVerificationResponse.java
  src/main/java/com/ssafy/tott/member/domain/MemberRepository.java
  src/main/java/com/ssafy/tott/member/domain/query/MemberRepositoryCustom.java
  src/main/java/com/ssafy/tott/member/domain/query/MemberRepositoryImpl.java
  src/main/java/com/ssafy/tott/member/exception/MemberErrorCode.java
  src/main/java/com/ssafy/tott/member/mapper/MemberMapper.java
  src/main/java/com/ssafy/tott/member/service/MemberService.java
  src/main/java/com/ssafy/tott/member/service/MemberVerificationService.java
  src/main/resources/application.yml
  src/test/java/com/ssafy/tott/api/kakao/module/KakaoAPITest.java
  src/test/java/com/ssafy/tott/api/shinhan/ShinhanBankAPITest.java
  src/test/java/com/ssafy/tott/auth/service/AuthServiceTest.java
  src/test/java/com/ssafy/tott/global/fixture/MemberFixture.java
  src/test/java/com/ssafy/tott/housedetail/repository/HouseDetailRepositoryTest.java
  src/test/java/com/ssafy/tott/housedetail/service/HouseDetailServiceTest.java
  src/test/java/com/ssafy/tott/housegeo/repository/HouseGeoRepositoryTest.java
  src/test/java/com/ssafy/tott/housegeo/service/HouseGeoServiceTest.java
  src/test/java/com/ssafy/tott/member/service/MemberServiceTest.java
  src/test/java/com/ssafy/tott/member/service/MemberVerificationServiceTest.java
  src/test/java/com/ssafy/tott/region/repository/RegionRepositoryTest.java
  src/test/java/com/ssafy/tott/region/service/RegionServiceTest.java
Labels: ✨ feature

#60 OPEN API 모듈 구조를 변경
  src/main/java/com/ssafy/tott/account/service/AccountService.java
  src/main/java/com/ssafy/tott/api/core/APIResponse.java
  src/main/java/com/ssafy/tott/api/core/FetchAPICore.java
  src/main/java/com/ssafy/tott/api/core/dto/APIRequest.java
  src/main/java/com/ssafy/tott/api/core/dto/APIResponse.java
  src/main/java/com/ssafy/tott/api/core/dto/request/APIJsonRequest.java
  src/main/java/com/ssafy/tott/api/core/dto/request/APIPagingRequest.java
  src/main/java/com/ssafy/tott/api/core/dto/request/APIQueryRequest.java
  src/main/java/com/ssafy/tott/api/kakao/data/dto/request/KakaoAPIRequest.java
  src/main/java/com/ssafy/tott/api/kakao/data/dto/response/KakaoAPIResponse.java
  src/main/java/com/ssafy/tott/api/kakao/service/KakaoMapFetchAPI.java
  src/main/java/com/ssafy/tott/api/seoulopendata/data/dto/request/RentAPIRequest.java
  src/main/java/com/ssafy/tott/api/seoulopendata/data/dto/response/RentAPIResponse.java
  src/main/java/com/ssafy/tott/api/seoulopendata/service/SeoulOpenDataRentHouseFetchAPI.java
  src/main/java/com/ssafy/tott/api/seoulopendata/service/SeoulOpenDataService.java
  src/main/java/com/ssafy/tott/api/shinhan/ShinhanBankAPI.java
  src/main/java/com/ssafy/tott/api/shinhan/dto/response/ShinhanBankAPIResponse.java
  src/main/java/com/ssafy/tott/api/shinhan/service/searchaccounts/dto/ShinhanBankSearchAccountsFetchAPI.java
  src/main/java/com/ssafy/tott/api/shinhan/service/searchaccounts/dto/request/ShinhanBankSearchAccountsRequest.java
  src/main/java/com/ssafy/tott/api/shinhan/service/searchname/ShinhanBankSearchNameFetchAPI.java
  src/main/java/com/ssafy/tott/api/shinhan/service/searchname/dto/request/ShinhanBankSearchNameRequest.java
  src/main/java/com/ssafy/tott/api/shinhan/service/transfer1/ShinhanBankTransfer1FetchAPI.java
  src/main/java/com/ssafy/tott/api/shinhan/service/transfer1/dto/request/ShinhanBankTransfer1Request.java
  src/main/java/com/ssafy/tott/member/service/MemberService.java
  src/test/java/com/ssafy/tott/api/seoul/HouseAPITest.java
  src/test/java/com/ssafy/tott/api/shinhan/ShinhanBankAPITest.java
  src/test/java/com/ssafy/tott/member/service/MemberServiceTest.java
Labels: ✨ feature, ♻️ refactor

#63 집 정보 조회 API를 구현
  src/main/java/com/ssafy/tott/api/core/FetchRetry.java
  src/main/java/com/ssafy/tott/api/core/FetchRetryImpl.java
  src/main/java/com/ssafy/tott/housedetail/controller/HouseDetailController.java
  src/main/java/com/ssafy/tott/housedetail/data/cond/HouseDetailRecentViewCond.java
  src/main/java/com/ssafy/tott/housedetail/data/dto/request/HouseDetailRecentViewRequest.java
  src/main/java/com/ssafy/tott/housedetail/data/dto/response/HouseDetailRecentViewResponse.java
  src/main/java/com/ssafy/tott/housedetail/data/vo/HouseDetailRecentViewVO.java
  src/main/java/com/ssafy/tott/housedetail/domain/HouseDetailRepository.java
  src/main/java/com/ssafy/tott/housedetail/domain/query/HouseDetailRepositoryCustom.java
  src/main/java/com/ssafy/tott/housedetail/domain/query/HouseDetailRepositoryImpl.java
  src/main/java/com/ssafy/tott/housedetail/service/HouseDetailService.java
  src/main/java/com/ssafy/tott/member/mapper/MemberMapper.java
Labels: ✨ feature

#65 비밀번호 검증 기능 구현
  src/main/java/com/ssafy/tott/member/data/dto/request/MemberSignupRequest.java
  src/main/java/com/ssafy/tott/member/domain/embbeded/Password.java
  src/main/java/com/ssafy/tott/member/exception/MemberErrorCode.java
  src/main/java/com/ssafy/tott/member/mapper/MemberMapper.java
Labels: ✨ feature

#68 전세 대출 한도 조회 API 를 호출하는 기능을 구현한다
  src/main/java/com/ssafy/tott/api/shinhan/ShinhanBankAPI.java
  src/main/java/com/ssafy/tott/api/shinhan/service/searchaccounts/ShinhanBankSearchAccountsFetchAPI.java
  src/main/java/com/ssafy/tott/api/shinhan/service/searchcreditline/ShinhanBankSearchCreditLineFetchAPI.java
  src/main/java/com/ssafy/tott/api/shinhan/service/searchcreditline/dto/request/ShinhanBankSearchCreditLineRequest.java
  src/main/java/com/ssafy/tott/api/shinhan/service/searchcreditline/dto/request/ShinhanBankSearchCreditLineRequestBody.java
  src/main/java/com/ssafy/tott/api/shinhan/service/searchcreditline/dto/response/ShinhanBankSearchCreditLineResponse.java
  src/main/java/com/ssafy/tott/api/shinhan/service/searchcreditline/dto/response/body/ShinhanBankSearchCreditLineResponseDataBody.java
Labels: ✨ feature

#73 스프링 시큐리티 설정및 URI 수정
  src/main/java/com/ssafy/tott/budget/controller/BudgetController.java
  src/main/java/com/ssafy/tott/global/security/SecurityConfig.java
  src/main/java/com/ssafy/tott/housegeo/controller/HouseGeoController.java
  src/main/java/com/ssafy/tott/wishlist/controller/WishlistController.java
Labels: ✨ feature

#74 계좌 번호와 금액을 랜덤으로 제공하는 기능을 구현
  src/main/java/com/ssafy/tott/account/service/AccountService.java
  src/main/java/com/ssafy/tott/api/shinhan/ShinhanBankAPI.java
  src/main/java/com/ssafy/tott/api/shinhan/service/searchaccounts/dto/response/ShinhanBankSearchAccountsResponse.java
  src/main/java/com/ssafy/tott/api/shinhan/service/searchaccounts/dto/response/body/ShinhanBankSearchAccountsResponseAccount.java
  src/test/java/com/ssafy/tott/api/shinhan/ShinhanBankAPITest.java
Labels: ✨ feature, ✅ test

#77 CheckWishList 기능
  src/main/java/com/ssafy/tott/housedetail/controller/HouseDetailController.java
  src/main/java/com/ssafy/tott/wishlist/controller/WishlistController.java
  src/main/java/com/ssafy/tott/wishlist/domain/WishlistRepository.java
  src/main/java/com/ssafy/tott/wishlist/dto/request/WishlistRemoveRequest.java
  src/main/java/com/ssafy/tott/wishlist/dto/response/WishlistCheckResponse.java
  src/main/java/com/ssafy/tott/wishlist/dto/response/WishlistCreateResponse.java
  src/main/java/com/ssafy/tott/wishlist/dto/response/WishlistViewResponse.java
  src/main/java/com/ssafy/tott/wishlist/service/WishlistService.java
  src/test/java/com/ssafy/tott/wishlist/repository/WishlistRepositoryTest.java
  src/test/java/com/ssafy/tott/wishlist/service/WishlistServiceMockTest.java
  src/test/java/com/ssafy/tott/wishlist/service/WishlistServiceTest.java
Labels: ✨ feature

#76 보증금 설정을 통한 전세 대출 한도 설정 기능을 구현
  src/main/java/com/ssafy/tott/api/shinhan/ShinhanBankAPI.java
  src/main/java/com/ssafy/tott/api/shinhan/controller/ShinhanBankController.java
  src/main/java/com/ssafy/tott/api/shinhan/service/searchcreditline/dto/request/ShinhanBankSearchCreditLineRequestBody.java
  src/main/java/com/ssafy/tott/api/shinhan/service/searchcreditline/dto/response/ShinhanBankSearchCreditLineResponse.java
  src/main/java/com/ssafy/tott/auth/service/AuthService.java
  src/main/java/com/ssafy/tott/budget/controller/BudgetController.java
  src/main/java/com/ssafy/tott/budget/service/BudgetService.java
  src/main/java/com/ssafy/tott/member/controller/MemberController.java
  src/main/java/com/ssafy/tott/member/domain/Member.java
  src/main/java/com/ssafy/tott/member/mapper/MemberMapper.java
  src/main/java/com/ssafy/tott/member/service/MemberService.java
Labels: ✨ feature

#79 API 명세를 수정한다
  src/main/java/com/ssafy/tott/housedetail/controller/HouseDetailController.java
  src/main/java/com/ssafy/tott/housedetail/data/vo/HouseDetailRecentViewVO.java
  src/main/java/com/ssafy/tott/housegeo/controller/HouseGeoController.java
  src/test/java/com/ssafy/tott/budget/service/BudgetServiceTest.java
  src/test/java/com/ssafy/tott/global/fixture/MemberFixture.java
Labels: ✨ feature

#81 집 매물의 변동 정보를 제공하는 기능을 구현
  src/main/java/com/ssafy/tott/api/shinhan/ShinhanBankAPI.java
  src/main/java/com/ssafy/tott/api/shinhan/controller/ShinhanBankController.java
  src/main/java/com/ssafy/tott/api/shinhan/service/searchcreditline/dto/response/ShinhanBankSearchCreditLineResponse.java
  src/main/java/com/ssafy/tott/housedetail/controller/HouseDetailController.java
  src/main/java/com/ssafy/tott/housedetail/data/dto/response/HouseDetailStateResponse.java
  src/main/java/com/ssafy/tott/housedetail/data/vo/HouseDetailStateVO.java
  src/main/java/com/ssafy/tott/housedetail/service/HouseDetailService.java
Labels: ✨ feature

#82 Region 목록를 조회하는 기능 구현
  src/main/java/com/ssafy/tott/region/controller/RegionController.java
  src/main/java/com/ssafy/tott/region/data/dto/response/DistrictResponse.java
  src/main/java/com/ssafy/tott/region/data/dto/response/LegalDongResponse.java
  src/main/java/com/ssafy/tott/region/data/vo/DistrictVO.java
  src/main/java/com/ssafy/tott/region/data/vo/LegalDongVO.java
  src/main/java/com/ssafy/tott/region/domain/query/RegionRepositoryCustom.java
  src/main/java/com/ssafy/tott/region/domain/query/RegionRepositoryImpl.java
  src/main/java/com/ssafy/tott/region/service/RegionService.java
  src/test/java/com/ssafy/tott/region/repository/RegionRepositoryTest.java
Labels: ✨ feature

#84 집 매물의 변동 정보를 제공하는 기능을 검증한다.
  src/test/java/com/ssafy/tott/housedetail/service/HouseDetailServiceTest.java
Labels: ✅ test

#85 Response 에러 코드를 body에 넣어서 전달
  src/main/java/com/ssafy/tott/global/exception/dto/response/ExceptionResponse.java
  src/main/java/com/ssafy/tott/housedetail/controller/HouseDetailController.java
  src/main/java/com/ssafy/tott/member/domain/embbeded/Email.java
  src/main/java/com/ssafy/tott/member/domain/embbeded/PhoneNumber.java
  src/main/java/com/ssafy/tott/member/exception/MemberErrorCode.java
Labels: ✨ feature

#89 공공데이터를 최신만 보여주는 기능을 구현
  src/main/java/com/ssafy/tott/api/seoulopendata/data/cond/ExistByDetailCond.java
  src/main/java/com/ssafy/tott/api/seoulopendata/service/SeoulOpenDataService.java
  src/main/java/com/ssafy/tott/global/domain/BaseEntity.java
  src/main/java/com/ssafy/tott/housedetail/domain/query/HouseDetailRepositoryCustom.java
  src/main/java/com/ssafy/tott/housedetail/domain/query/HouseDetailRepositoryImpl.java
  src/main/java/com/ssafy/tott/housedetail/service/HouseDetailService.java
  src/main/java/com/ssafy/tott/housegeo/domain/query/HouseGeoRepositoryImpl.java
  src/main/java/com/ssafy/tott/housegeo/service/HouseGeoService.java
Labels: ✨ feature

#91 공공데이터 업데이트 기능을 구현
  src/main/java/com/ssafy/tott/api/seoulopendata/data/cond/ExistByDetailCond.java
  src/main/java/com/ssafy/tott/api/seoulopendata/service/SeoulOpenDataService.java
  src/main/java/com/ssafy/tott/global/domain/BaseEntity.java
  src/main/java/com/ssafy/tott/housedetail/domain/query/HouseDetailRepositoryCustom.java
  src/main/java/com/ssafy/tott/housedetail/domain/query/HouseDetailRepositoryImpl.java
  src/main/java/com/ssafy/tott/housedetail/service/HouseDetailService.java
  src/main/java/com/ssafy/tott/housegeo/domain/query/HouseGeoRepositoryImpl.java
  src/main/java/com/ssafy/tott/housegeo/service/HouseGeoService.java
Labels: ✨ feature

#90 찜목록 조회 API request 수정
  src/main/java/com/ssafy/tott/api/infra/SchedulerConfig.java
  src/main/java/com/ssafy/tott/housegeo/domain/HouseGeo.java
  src/main/java/com/ssafy/tott/wishlist/domain/query/WishlistRepositoryImpl.java
  src/main/java/com/ssafy/tott/wishlist/dto/response/WishlistViewResponse.java
  src/main/java/com/ssafy/tott/wishlist/service/WishlistService.java
  src/main/java/com/ssafy/tott/wishlist/vo/WishlistVO.java
  src/test/java/com/ssafy/tott/global/fixture/MemberFixture.java
  src/test/java/com/ssafy/tott/member/domain/embbeded/PhoneNumberTest.java
Labels: ✨ feature

#93 계좌 관련 API를 구현
  src/main/java/com/ssafy/tott/account/controller/AccountController.java
  src/main/java/com/ssafy/tott/account/data/dto/response/FindMoneyResponse.java
  src/main/java/com/ssafy/tott/account/service/AccountService.java
  src/main/java/com/ssafy/tott/housedetail/service/HouseDetailService.java
Labels: ✨ feature

#94 API 재호출하는 기능을 구현
  src/main/java/com/ssafy/tott/api/shinhan/service/searchaccounts/dto/response/body/ShinhanBankSearchAccountsResponseAccount.java
  src/main/java/com/ssafy/tott/api/shinhan/service/searchcreditline/ShinhanBankSearchCreditLineFetchAPI.java
Labels: ✨ feature
